version: '3.1'
services:

  app:
    container_name: reading-is-good
    image: reading-is-good
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - mongo_net


  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    hostname: localhost
    restart: always
    environment:
      - MONGO_DB_HOSTNAME=localhost
      - MONGO_DB_NAME=readingisgood
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge

